query DBSearchQuery($limit: Int, $offset: Int, $searchTerm: String, $categories: String, $items: String, $weapons: String, $imagine: String, $enemies: String, $skills: String, $maps: String) @load {
    entries(searchTerm: $searchTerm, categories: $categories, limit: $limit, offset: $offset, items: $items, weapons: $weapons, imagine: $imagine, enemies: $enemies, skills: $skills, maps: $maps) @paginate(mode: SinglePage) {
        totalResults
        hasNextPage
        hasPreviousPage
        results {
            __typename
            id
            name {
                ja_JP
                en_US
            }
            thumb
            subcategoryName {
                ja_JP
                en_US
            }
            ... on Weapon {
                classImg
                elementImg
                attribute
            }
            ... on Skill {
                elementImg
                skillBackgroundImg
                skill_type
            }
            ... on Imagine {
                elementImg
            }
        }
    }
}