query DBSearchQuery($offset: Int, $searchTerm: String, $categories: String, $items: String, $weapons: String) @load {
    entries(searchTerm: $searchTerm, categories: $categories, limit: 10, offset: $offset, items: $items, weapons: $weapons) @paginate(mode: SinglePage) {
        totalResults
        results {
            __typename
            id
            name {
                ja_JP
                en_US
            }
            thumb
            subcategoryName {
                ja_JP
                en_US
            }
            ... on Weapon {
                classImg
                elementImg
                attribute
            }
            ... on Skill {
                elementImg
                skillBackgroundImg
                skill_type
            }
            ... on Imagine {
                elementImg
            }
        }
    }
}