[{
    "Category2": "",
    "SortId": 10000,
    "ID": "cty01_3",
    "MaxMountNum": 1,
    "Category": 1,
    "IconPosition": {
        "Y": 0,
        "X": 0
    },
    "AreaName": "子供たちのための鍛錬",
    "TermId": 0,
    "RequestDetailText": "うちでは子供たちに護身術なんかを教えて、いろいろ鍛えてるんだけどね。今度、マウントイマジンと競走させてやろうと思ってさ。いざっていう時、自分の身を守れるのはやっぱり自分だ。日頃から運動して鍛えておくのは大事だよ。ということで、マウントイマジンを貸してもらえるかい？",
    "TimeData": [{
        "BaseTime": 300,
        "Reward": {
            "CertaintyReward": ["MC_cty01_3_05_1N_00100"],
            "RandomReward": [{
                "TypeCount": 1,
                "List": [{
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_3_05_1R_00100"
                }, {
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_3_05_1R_00200"
                }, {
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_3_05_1R_00300"
                }, {
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_3_05_1R_00400"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_3_05_1R_00500"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_3_05_1R_00600"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_3_05_1R_00700"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_3_05_1R_00800"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_3_05_1R_00900"
                }, {
                    "Weight": 5000,
                    "TypeCount": 1,
                    "Lottery": 50,
                    "Reward": "MC_cty01_3_05_1R_01000"
                }]
            }]
        },
        "Exp": 5,
        "ID": "cty01_3_05",
        "MaxAddNum": 20
    }],
    "LimitData": [],
    "NextExp": 0,
    "ExpeditionCount": 0,
    "Level": 0,
    "ShorteningEffect": 0,
    "RequesterName": "孤児院の院長リザ",
    "NowExp": 0,
    "Rare": false
}, {
    "Category2": "",
    "SortId": 10000,
    "ID": "cty01_4",
    "MaxMountNum": 1,
    "Category": 1,
    "IconPosition": {
        "Y": 0,
        "X": 0
    },
    "AreaName": "バチッとキメるっしょ！",
    "TermId": 0,
    "RequestDetailText": "おいッス～☆　最近マウントイマジンにハマってんの！　イカしたマウントに乗って出勤とかバチバチにキマってね？　冒険者さんの自慢のマウントもアピールするからさ。少～しの間でいいから貸してくんね？　これもイマジンの研究ってヤツよ！　ヨ・ロ・シ・ク！",
    "TimeData": [{
        "BaseTime": 300,
        "Reward": {
            "CertaintyReward": ["MC_cty01_4_05_1N_00100"],
            "RandomReward": [{
                "TypeCount": 1,
                "List": [{
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_4_05_1R_00100"
                }, {
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_4_05_1R_00200"
                }, {
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_4_05_1R_00300"
                }, {
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_4_05_1R_00400"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_4_05_1R_00500"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_4_05_1R_00600"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_4_05_1R_00700"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_4_05_1R_00800"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_4_05_1R_00900"
                }, {
                    "Weight": 5000,
                    "TypeCount": 1,
                    "Lottery": 50,
                    "Reward": "MC_cty01_4_05_1R_01000"
                }]
            }]
        },
        "Exp": 5,
        "ID": "cty01_4_05",
        "MaxAddNum": 20
    }],
    "LimitData": [],
    "NextExp": 0,
    "ExpeditionCount": 0,
    "Level": 0,
    "ShorteningEffect": 0,
    "RequesterName": "最近ノッてるフオヴィ",
    "NowExp": 0,
    "Rare": false
}, {
    "Category2": "",
    "SortId": 10000,
    "ID": "cty01_1",
    "MaxMountNum": 1,
    "Category": 1,
    "IconPosition": {
        "Y": 0,
        "X": 0
    },
    "AreaName": "小さな幸せを",
    "TermId": 0,
    "RequestDetailText": "うちの息子が大のマウントイマジン好きなんです。その息子が近いうちに誕生日を迎えます。なのでサプライズとして、マウントイマジンを使ってプレゼントを届けようと思うのです。私はマウントイマジンを持っていませんので、少しの間マウントイマジンを貸していただけないでしょうか？",
    "TimeData": [{
        "BaseTime": 300,
        "Reward": {
            "CertaintyReward": ["MC_cty01_1_05_1N_00100"],
            "RandomReward": [{
                "TypeCount": 1,
                "List": [{
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_1_05_1R_00100"
                }, {
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_1_05_1R_00200"
                }, {
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_1_05_1R_00300"
                }, {
                    "Weight": 250,
                    "TypeCount": 1,
                    "Lottery": 2.5,
                    "Reward": "MC_cty01_1_05_1R_00400"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_1_05_1R_00500"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_1_05_1R_00600"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_1_05_1R_00700"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_1_05_1R_00800"
                }, {
                    "Weight": 800,
                    "TypeCount": 1,
                    "Lottery": 8,
                    "Reward": "MC_cty01_1_05_1R_00900"
                }, {
                    "Weight": 5000,
                    "TypeCount": 1,
                    "Lottery": 50,
                    "Reward": "MC_cty01_1_05_1R_01000"
                }]
            }]
        },
        "Exp": 5,
        "ID": "cty01_1_05",
        "MaxAddNum": 20
    }],
    "LimitData": [],
    "NextExp": 0,
    "ExpeditionCount": 0,
    "Level": 0,
    "ShorteningEffect": 0,
    "RequesterName": "子を思う父親",
    "NowExp": 0,
    "Rare": false
}]